import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletContextProvider } from "@/components/WalletProvider";
import { NavigationProvider } from "@/components/NavigationProvider";
import { AuthProvider } from "@/components/AuthProvider";
import { SignatureProvider } from "@/components/SignatureProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletContextProvider>
          <AuthProvider>
            <SignatureProvider>
              <NavigationProvider>
                {children}
              </NavigationProvider>
            </SignatureProvider>
          </AuthProvider>
        </WalletContextProvider>
      </body>
    </html>
  );
}
